### PR TITLE
Fix SimpleBatcher apparent deadlock #2196

### LINKED ISSUE #2196: SimpleBatcher apparent deadlock
I am using version 6.2.0.RELEASE.
I would like to ask about the Batch Execution using asynchronous commands like [wiki](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces).
```java
@BatchSize(50)
interface StringCommands extends Commands {
    RedisFuture<String> get(String key, CommandBatching batching);
}

StringCommands commands = …
commands.get("key1", CommandBatching.queue());
commands.get("key2", CommandBatching.flush()); 
```
If the above codes run with multi threads, sometimes RedisFuture.get() will block for ever, actually some commands are not send to the Redis Server.
It might caused by io.lettuce.core.dynamic.SimpleBatcher#flush(boolean), "while (flushing.compareAndSet(false, true))".

Thank you!

### PR DESCRIPTION
**Pull request by ggivo**
Closes #2196 

### Problem:
- **Flush Operation Conflict:**
  - When one thread (T1) performs a flush, it may read and dispatch batched commands before resetting the `flushing` flag.
  - If another thread (T2) adds a command and forced flush at this moment. Command might be added to the queue but does not trigger a flush.
  - As a result, the command remains in the queue until the next flush request, causing a delay in dispatching.

- **Flag Reset Between Iterations:**
  - During a default flush operation, if multiple batches are processed, the `flushing` flag is reset between iterations.
  - This allows another thread to take over, potentially causing the initial thread to return `BatchTasks.EMPTY` instead of properly processed commands.

> 1. T1 -> batch(command, CommandBatching.flush()
> 2. T1 -> flushing.compareAndSet(false, true) == true
> 3. T1 -> flush()->doFlush()
> 4. T2 -> batch(command, CommandBatching.flush()
> 5. T2 -> flushing.compareAndSet(false, true) == false  #already flushing will skip doFlush  and command remain not dispatched
> 6. T1 -> batch() completes
> 7. T2 -> batch() completes

### Fix: 
If force flush is requested while flushing, perform additional flush iteration after ongoing completes

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You applied code formatting rules using the `mvn formatter:format` target. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

File: src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java [hunk 1]
```diff
@@ -51,6 +52,11 @@ class SimpleBatcher implements Batcher {
 
     private final AtomicBoolean flushing = new AtomicBoolean();
 
+    // foreFlushRequested indicates that a flush was requested while there is already a flush in progress
```
Comment (tishun) [inline src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java:55]:
```suggestion
    // forceFlushRequested indicates that a flush was requested while there is already a flush in progress
```

File: src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java [hunk 2]
```diff
@@ -95,37 +101,55 @@ protected BatchTasks flush(boolean forcedFlush) {
...
+                }
 
-            } finally {
-                flushing.set(false);
+                if (commands.isEmpty()) {
+                    return BatchTasks.EMPTY;
+                } else {
+                    // Could happen if default flush is started in t1 and in case
+                    // there are multiple default batches to process another thread
+                    // acquires flushing flag in-between t1 releases flushing flag & try to acquire it again
```
Comment (tishun) [inline src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java:148]: Can we try to simplify this? I am reading it for the n-th time and it is really complex.

**Review by tishun — APPROVED** [review]
My head really hurts after reading this code, but I am not sure I can simplify it any more than you have.

Perhaps we need to do some bigger refactoring around the flushing logic, but this bug is not the time.

File: src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (tishun) [reply src/main/java/io/lettuce/core/dynamic/SimpleBatcher.java]: Awesome!
