### PR TITLE
ERR unknown subcommand 'MYID' with Azure Managed Redis #3495

### LINKED ISSUE #3495: ERR unknown subcommand 'MYID' with Azure Managed Redis (High Availablity)
#### Current Behavior

Intermittent Error / Exception when using RedisClusterConfiguration to Connect with Azure Managed Redis with High Availablity enabled.

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.RedisCommandExecutionException: ERR unknown subcommand 'MYID'
 at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:151)
 at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:120)
 at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:124)
 at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:115)
 at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:67)
 at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:67)
 at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:50)
 at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:67)
 at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:67)
 at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:769)
 at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:704)
 at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:621)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1519)
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1377) 
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1428)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
 at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
 at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

#### Input Code

```java
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

@CustomLog
@Configuration
@EnableCaching
@EnableRetry
public class ApplicationCacheConfiguration {
   

    @Bean(name = REDIS_CACHE_MANAGER)
    @Primary
    public CacheManager redisCacheManager(RedisConnectionFactory redisConnectionFactory,
                                          RedisCacheConfiguration customerCacheConfiguration) {
        Map<String, RedisCacheConfiguration> cacheConfigurations = new HashMap<>();
        cacheConfigurations.put(CUSTOMER_CACHE, customerCacheConfiguration);

        return RedisCacheManager.builder(RedisCacheWriter.nonLockingRedisCacheWriter(redisConnectionFactory))
                .withInitialCacheConfigurations(cacheConfigurations)
                .build();
    }



    @Bean
    public RedisCacheConfiguration customerCacheConfiguration() {
        // This is the recommended way to specify a whitelist for a small range
        return RedisCacheConfiguration.defaultCacheConfig()
                .serializeKeysWith(RedisSerializationContext.SerializationPair.fromSerializer(new StringRedisSerializer()))
                .serializeValuesWith(RedisSerializationContext.SerializationPair.fromSerializer(new FastJsonRedisSerializer<>(Customer.class)))
                .entryTtl(Duration.ofSeconds(redisCustomerCacheTtlInSeconds));
    }

    @Bean
    public RedisConnectionFactory redisConnectionFactory(LettucePoolingClientConfiguration lettucePoolingClientConfiguration) {
        RedisConfiguration redisConfiguration;
        if (useRedisSentinel) {
            RedisSentinelConfiguration sentinelConfiguration = new RedisSentinelConfiguration()
                    .master("mymaster") // Needs to be in sync with the Redis Helm configuration
                    .sentinel(redisHostName, redisPort); // Note: redisPort == sentinelPort in this case
            sentinelConfiguration.setPassword(RedisPassword.of(redisPassword));
            sentinelConfiguration.setSentinelPassword(RedisPassword.of(redisPassword));
            redisConfiguration = sentinelConfiguration;
        } else if (useCluster) {
            // When useRedisSentinel is false and useCluster is true, connect to Azure Managed Redis in cluster mode
            RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration();
            clusterConfiguration.addClusterNode(new RedisClusterNode(redisHostName, redisPort));
            clusterConfiguration.setPassword(RedisPassword.of(azureRedisPassword));
            redisConfiguration = clusterConfiguration;
        } else {
            // Standalone Azure Managed Redis
            RedisStandaloneConfiguration standaloneConfiguration = new RedisStandaloneConfiguration(redisHostName, redisPort);
            standaloneConfiguration.setPassword(RedisPassword.of(azureRedisPassword));
            redisConfiguration = standaloneConfiguration;
        }

        LettuceConnectionFactory lettuceConnectionFactory = new
                LettuceConnectionFactory(redisConfiguration, lettucePoolingClientConfiguration);
        // remember the app settings
        lettuceConnectionFactory.afterPropertiesSet();
        log.atInfo()
                .with(ApplicationConstants.LOG_SESSION_CACHE_SIZE, JSON.toJSONString(lettucePoolingClientConfiguration))
                .log("Building lettuce connection pool");
        return lettuceConnectionFactory;
    }

    @Bean
    public LettucePoolingClientConfiguration lettucePoolingClientConfiguration(GenericObjectPoolConfig<StatefulConnection<?, ?>> genericObjectPoolConfig) {
        SocketOptions socketOptions = SocketOptions.builder()
                .connectTimeout(Duration.ofSeconds(redisConnectionTimeoutInSeconds))
                .keepAlive(true) // Enable TCP keepalive for long-lived connections
                .build();
        ClientOptions clientOptions = ClientOptions.builder()
                .socketOptions(socketOptions)
                .autoReconnect(true)
                .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .build();

        LettucePoolingClientConfiguration.LettucePoolingClientConfigurationBuilder lettucePoolingClientConfigurationBuilder = LettucePoolingClientConfiguration.builder()
                .clientOptions(clientOptions)
                .commandTimeout(Duration.ofSeconds(redisCommandTimeoutInSeconds))
                .poolConfig(genericObjectPoolConfig);

        if (useRedisSentinel) {
            // Only in real Sentinel environments
            lettucePoolingClientConfigurationBuilder.readFrom(ReadFrom.REPLICA_PREFERRED);
        }
        // Enable SSL/TLS for Azure Redis Enterprise
        if (isSslEnabled) {
            lettucePoolingClientConfigurationBuilder
                    .useSsl()
                    .disablePeerVerification(); // Required for Azure private endpoints with self-signed certs
        }
        return lettucePoolingClientConfigurationBuilder.build();
    }

    @Bean
    @SuppressWarnings("java:S1452")
    public GenericObjectPoolConfig<StatefulConnection<?, ?>> genericObjectPoolConfig() {
        GenericObjectPoolConfig<StatefulConnection<?, ?>> poolConfig = new GenericObjectPoolConfig<>();
        poolConfig.setMaxIdle(maxIdle);
        poolConfig.setMinIdle(minIdle);
        poolConfig.setMaxWait(Duration.ofMillis(maxWaitMillis));
        poolConfig.setMaxTotal(maxTotal);
        // Validation & eviction for stale connections
        poolConfig.setTestWhileIdle(true);
        poolConfig.setTimeBetweenEvictionRuns(Duration.ofMinutes(5));
        return poolConfig;
    }


    public boolean isClubMetadataCacheEnabled() {
        return isDbCacheEnabled;
    }
}
```

<details>

<summary>Input Code</summary>

```java
import org.springframework.data.redis.connection.*;

RedisClusterConfiguration clusterConfiguration = new RedisClusterConfiguration();
clusterConfiguration.addClusterNode(new RedisClusterNode(redisHostName, redisPort));
clusterConfiguration.setPassword(RedisPassword.of(azureRedisPassword));
redisConfiguration = clusterConfiguration;
```
</details>

#### Expected behavior/code

No MYID Error when using RedisClusterConfiguration

#### Environment

- Java 25
- Spring Boot Version 3.5.7
- Azure Managed Redis with High Availability Enabled and with OSSCluster policy
- Lettuce version(s): 6.6.0.RELEASE
- Redis version: 7.4

### PR DESCRIPTION
**Pull request by tishun**
This PR improves the resiliency of the driver in environments that do not support the full set of `CLUSTER` commands.
Notable examples are all Redis Enterprise - based environments that still operate in the OSS Cluster mode.

To avoid putting the driver in an invalid state we resort to extracting the data about the current cluster ID by issuing a `CLUSTER NODES` command and parsing the line that contains information about `myself`.

For users of installations that support the `CLUSTER MYID` there should be no behavioral difference.

Closes #3495 

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You applied code formatting rules using the `mvn formatter:format` target. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

 

---

> [!NOTE]
> **Medium Risk**
> Changes `clusterMyId()` behavior in both async and reactive cluster commands, which can affect cluster routing/topology logic when errors occur. Risk is mitigated by narrow fallback conditions and added unit/integration coverage.
> 
> **Overview**
> Improves resiliency of `clusterMyId()` for cluster connections by **falling back to parsing `CLUSTER NODES`** (selecting the `MYSELF` nodeId) when `CLUSTER MYID` is unsupported/denied or returns empty.
> 
> Applies the fallback to both `AbstractRedisAsyncCommands` (via `CompletableFuture` composition and `PipelinedRedisFuture`) and `AbstractRedisReactiveCommands` (via `onErrorResume`/`switchIfEmpty`), and adds new unit + integration tests to cover success, fallback, error propagation, and missing-`MYSELF` scenarios.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9bce1bc9eb910e80e18eaf0d684d03dd36eb03a2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java [hunk 1]
```diff
@@ -549,9 +552,55 @@ public RedisFuture<String> clusterMeet(String ip, int port) {
...
+    /**
+     * Extract the current node's ID by parsing {@code CLUSTER NODES} output.
+     *
+     * @return CompletableFuture containing the node ID if found, or failed future if no node has the MYSELF flag
+     */
+    private CompletableFuture<String> clusterMyIdFromClusterNodes() {
+        return clusterNodes().toCompletableFuture()
+                .thenApply(nodes -> io.lettuce.core.cluster.models.partitions.ClusterPartitionParser.parse(nodes).stream()
+                        .filter(node -> node.is(io.lettuce.core.cluster.models.partitions.RedisClusterNode.NodeFlag.MYSELF))
+                        .findFirst().map(io.lettuce.core.cluster.models.partitions.RedisClusterNode::getNodeId)
```
Comment (tishun) [inline src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java]: io.lettuce.core.cluster.models.partitions.RedisClusterNode to import

File: src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java [hunk 2]
```diff
@@ -549,9 +552,55 @@ public RedisFuture<String> clusterMeet(String ip, int port) {
...
+    }
+
+    /**
+     * Extract the current node's ID by parsing {@code CLUSTER NODES} output.
+     *
+     * @return CompletableFuture containing the node ID if found, or failed future if no node has the MYSELF flag
+     */
+    private CompletableFuture<String> clusterMyIdFromClusterNodes() {
+        return clusterNodes().toCompletableFuture()
+                .thenApply(nodes -> io.lettuce.core.cluster.models.partitions.ClusterPartitionParser.parse(nodes).stream()
```
Comment (tishun) [inline src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java]: io.lettuce.core.cluster.models.partitions.ClusterPartitionParser to import
