### PR TITLE
Send the CLIENT SETINFO command in a fire-and-forget way

### LINKED ISSUE #2817: Connection handshake fails with `ERR unknown command CLIENT, with args beginning with: SETINFO lib-name`
#### Current Behavior

The connection does not work and fails to connect to Google Cloud Redis (Memory Store) v7.2 with the following error CLIENT 'SETINFO'. The Client Setinfo not supported by GCP Redis

<details>
<summary>Stack trace</summary>

```java
Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to IP_ADDRESS/<unresolved>:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:350)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:215)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:200)
	at com.wayfair.smart.ds587.demo.bt.graphql.RedisTest.main(RedisTest.java:29)
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown command 'CLIENT', with args beginning with: 'SETINFO' 'lib-name' 'Lettuce'
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:745)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:680)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): 6.3.2.RELEASE
- Redis version: Google Cloud Redis (Memory Store) v7.2

### PR DESCRIPTION
**Pull request by tishun**
Closes #2817 

This solution aims to bring consistency between the Lettuce driver and most other drivers maintained by the Redis team.
The current approach is - instead of probing for the version of the remote server and deciding based on that wether or not to send the CLIENT SETINFO command - to always send it and ignore the server response. There are two main reasons behind this: different flavors of the Redis server handle this in different versions and also the information sent is not critical to the operation of the driver, so failures should not necessary terminate the connection.

1. Tested against Redis 6.0 - verified no connection failures are shown
2. Tested against Redis  (unstable) - verified no connection failures are shown; and that CLIENT LIST contains the expected data on the `lib-name` and `lib-ver` are set properly.
3. Added unit tests

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

File: src/main/java/io/lettuce/core/RedisHandshake.java [hunk 1]
```diff
@@ -281,6 +270,25 @@ private CompletableFuture<Void> applyPostHandshake(Channel channel, String redis
         return dispatch(channel, postHandshake);
     }
 
+    private CompletableFuture<Void> applyFireAndForget(Channel channel) {
```
Comment (mp911de) [inline src/main/java/io/lettuce/core/RedisHandshake.java:273]: to be fair, the method name doesn't reflect what is happening here as lenient error handling happens in the calling code.

Looking at the code, it might make sense to introduce stronger guards to avoid `ArrayList` creation if neither library name nor library version are set and so avoid also the call to `dispatch`.

Just a couple of thoughts.

Comment (tishun) [reply src/main/java/io/lettuce/core/RedisHandshake.java:273]: Fair assessment :) Was a bit hasty with the change, will update with your suggestions. Thanks!

Comment (mp911de) [reply src/main/java/io/lettuce/core/RedisHandshake.java:273]: TBH, I'm not sure about fire+forget. 

There are quite some commands being invoked on startup and any failures can go unnoticed. Someone relying on the client name who has renamed the command doesn't find out about a failure until they investigate the client name on their own.

If someone encounters failures because of these commands, then they should not set the client name, library version, ….

What is the rationale to ignore errors?

Comment (tishun) [reply src/main/java/io/lettuce/core/RedisHandshake.java]: Could you give me an example where this metadata is critical to the operation of the client?
So far I assumed this is mostly tracing information. Are there flows where one client expects to find another one based on the name the other client provided? How would they handle this in older versions in Redis? I would be very hesitant to endorse the usage of these fields in this way

Even so I think the same rationale does not exist for lib-name and lib-version - these are definitely tracing information that is secondary to the operation of the driver.

Here is an excerpt from the documentation  for the [CLIENT SETINFO](https://redis.io/docs/latest/commands/client-setinfo/):

```
Client libraries are expected to pipeline this command after authentication on all connections and ignore failures since they could be connected to an older version that doesn't support them.
```

As I mentioned different flavors of the Redis server handle this in different versions and to embed a support matrix in the client would be counterproductive when the operation can simply fail. #2817 is a testament to this issue.

Would you consider it an improvement if we log the issue?

Comment (uglide) [reply src/main/java/io/lettuce/core/RedisHandshake.java]: @mp911de I am just adding my 2 cents here. Command renaming is seldom used nowadays because Redis provides more efficient ways to secure the connection, etc.

Comment (mp911de) [reply src/main/java/io/lettuce/core/RedisHandshake.java]: Probably logging at the debug level is a good common ground. That being said, `CLIENT SETNAME` belongs into the same category.

Comment (tishun) [reply src/main/java/io/lettuce/core/RedisHandshake.java]: Fair, let me prepare another change. Thanks for considering this!

Comment (tishun) [reply src/main/java/io/lettuce/core/RedisHandshake.java]: @mp911de what about this version?

**Review by mp911de — APPROVED** [review]
